spring:
  redis:
    host: 81.68.236.154
    password: lif314
    port: 6379
  # 服务发现
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.229.15:8848
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: 139.198.167.224:31267
#        clientIp:  192.168.133.1
    sentinel:
      transport:
        port: 8719
        dashboard: sentinel-service.xiaoji:8080

  # 模块名
  application:
    name: hcss-seckill
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
