spring:
  redis:
    host: 81.68.236.154
    password: lif314
    port: 6379
  # 服务发现
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.229.15:8848
    sentinel:
      transport:
        port: 8719
        dashboard: sentinel-service.xiaoji:8080

  # 模块名
  application:
    name: hcss-order
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  rabbitmq:
    addresses: 121.36.229.15
    port: 5672
    username: guest
    password: guest
    #虚拟主机地址
    virtual-host: /
    #连接超时时间
    connection-timeout: 15000
#    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    #消费端配置
    listener:
      simple:
        #消费端
        concurrency: 10
        #最大消费端数
        max-concurrency: 100
        #自动签收auto  手动 manual
        acknowledge-mode: manual
        #限流（海量数据，同时只能过来一条）
        prefetch: 1
    publisher-confirm-type: correlated
