spring:
  cloud:
    gateway:
      routes:
        # seckill
        - id: seckill_route
          uri: lb://hcss-seckill
          predicates:
            - Path=/api/seckill/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # order
        - id: order_route
          uri: lb://hcss-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # product
        - id: product_route
          uri: lb://hcss-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
    sentinel:
      transport:
        port: 8719
        dashboard: 139.198.167.224:31267
